FROM node:22-alpine AS build

ARG VITE_BE_URL=http://localhost:8000

WORKDIR /usr/src/app
COPY package*.json package-lock.json ./
RUN npm ci
COPY ./ ./
ENV VITE_BE_URL=${VITE_BE_URL}
RUN npm run build

FROM nginx:stable-alpine AS production

COPY --from=build /usr/src/app/nginx.conf /etc/nginx/conf.d
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
